### ISSUE TITLE
'webpack' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by sumedhkapoor** [DanWahlin/typescript-fundamentals#27]
When I run "npm run start" command on VS code terminal, I am getting error message "'webpack' is not recognized as an internal or external command," I have installed the dependencies using "npm install" command. Looks like webpack needs to be added in package.json as dev dependency. Currently following dev dependency are mentioned:
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^3.11.2"

Webpack should also be added here. For example:
    "webpack": "^5.55.0",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^3.11.2"

**Comment by DanWahlin** [comment]
Thanks @sumedhkapoor. Sorry you're hitting an issue with it.

After running npm install you should see webpack in the node_modules/.bin folder since webpack is part of the webpack-cli package. If you're not seeing that then I suspect something else is going on there that we'll have to account for. I just ran it from scratch on Mac and Windows and don't get an error due to webpack being put into the .bin folder during npm install.

Can you list your node version, npm version, and OS? I'm running npm 7.24.0 and Node 14.17.0 (Mac) and 14.17.6 (Windows) for example.

**Comment by sumedhkapoor** [comment]
Thanks @DanWahlin for your response and assistance.
I am on a Windows 10 machine with npm version 6.14.13 and node v14.17.2. In the node_modules/.bin folder I see only webpack-cli and webpack-dev-server. There is no webpack binary present.

**Comment by DanWahlin** [comment]
Thanks for the info. It could be related to 6.14.13....not sure. Can you do me a favor and delete note_modules and then re-run npm install? That way we'll know if something just wasn't installed right when it first ran. Normally webpack-cli handles the webpack installation part as mentioned earlier.

**Comment by sumedhkapoor** [comment]
Dan, I deleted node_modules folder and re-ran the npm install command. Still I got the same issue where webpack binary is not found. I think it is due to older npm version. Unfortunately I am unabe to update the npm version on my Windows system due to below error.
C:\windows\system32> npm --force -g install npm@latest
npm WARN using --force I sure hope you know what you are doing.
npm ERR! code EEXIST
npm ERR! path C:\Users\sumedh.kapoor\AppData\Local\Programs\nodejs\npm.cmd
npm ERR! Refusing to delete C:\Users\sumedh.kapoor\AppData\Local\Programs\nodejs\npm.cmd: is outside C:\Users\sumedh.kapoor\AppData\Local\Programs\nodejs\node_modules\npm and not a link
npm ERR! File exists: C:\Users\sumedh.kapoor\AppData\Local\Programs\nodejs\npm.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

**Comment by pigfin** [comment]
I get the same issue as sumedhkapoor - npm 6.14.15, Node 14.18.0, Windows 10.

**Comment by DanWahlin** [comment]
Good to know - thanks. Sounds like we may have to add webpack in there for now then. I'll look into it more and do some experiments.
 
@pigfin: For the time being you can do what @sumedhkapoor mentioned at the very top of the thread to get it going.

**Comment by DanWahlin** [comment]
I tried everything with the 7.x version of npm and it seems fine. Although webpack-cli is supposed to handle adding webpack, I added it into the dependencies for the project to handle this scenario. Grab the latest version and let me know if you hit any issues.

**Comment by pigfin** [comment]
Thanks @DanWahlin  will try shortly.

**Comment by DanWahlin** [comment]
No problem. Thanks to you and @sumedhkapoor for letting us know about that issue. Very weird that it's doing that, but rather catch those types of things early. Appreciate it.
