### ISSUE TITLE
Errors after running npm install

### ISSUE THREAD

**Issue by rsaclee** [DanWahlin/typescript-fundamentals#30]
Learning from Pluralsight, follow the instruction but got all kinds of errors after running npm install
npm ERR! code 1
npm ERR! path C:\Chung\typescript-fundamentals-main\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Chung\typescript-fundamentals-main\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=    
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Chung\\typescript-fundamentals-main\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@20.11.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - "python3" is not in PATH or produced an error
npm ERR! gyp verb find Python checking if "python" can be used
npm ERR! gyp verb find Python - executing "python" to get executable path
npm ERR! gyp verb find Python - "python" is not in PATH or produced an error
npm ERR! gyp verb find Python checking if "python2" can be used
npm ERR! gyp verb find Python - executing "python2" to get executable path
npm ERR! gyp verb find Python - "python2" is not in PATH or produced an error
npm ERR! gyp verb find Python checking if Python is C:\Python37\python.exe
npm ERR! gyp verb find Python - executing "C:\Python37\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Python37\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Python27\python.exe
npm ERR! gyp verb find Python - executing "C:\Python27\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Python27\python.exe" could not be run
npm ERR! gyp verb find Python checking if the py launcher can be used to find Python
npm ERR! gyp verb find Python - executing "py.exe" to get Python executable path
npm ERR! gyp verb find Python - "py.exe" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python2" can be used
npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if Python is C:\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Python27\python.exe
npm ERR! gyp ERR! find Python - "C:\Python27\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python
npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (C:\Chung\typescript-fundamentals-main\node_modules\node-gyp\lib\find-python.js:302:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (C:\Chung\typescript-fundamentals-main\node_modules\node-gyp\lib\find-python.js:136:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Chung\typescript-fundamentals-main\node_modules\node-gyp\lib\find-python.js:200:18)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (C:\Chung\typescript-fundamentals-main\node_modules\node-gyp\lib\find-python.js:266:16)
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:430:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Chung\\typescript-fundamentals-main\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Chung\typescript-fundamentals-main\node_modules\node-sass
npm ERR! gyp ERR! node -v v20.11.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

**Comment by DanWahlin** [comment]
I'm not able to duplicate that on my Windows machine so I'd check the following:

- Make sure you have the latest Node LTS version as mentioned in the readme
- Ensure your npm is up to date (it should be fine if you have the latest Node LTS version): `npm i -g npm`
- Delete the node_modules folder and package-lock.json file from the project root and try running `npm install` again

If you're still having issues then I'd need more information about your Windows setup to try to help.

**Comment by rsaclee** [comment]
I tried another machine and npm install was fine but got the following error

PS C:\Chung\typescript-fundamentals-main (2)\typescript-fundamentals-main> npm start

> ***@***.******@***.***> start
> webpack serve --mode development --open

C:\Chung\typescript-fundamentals-main (2)\typescript-fundamentals-main\node_modules\webpack-dev-server\lib\Server.js:2557
        throw error;
        ^

Error: listen EADDRINUSE: address already in use :::9000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at READ_WRITE (C:\Chung\typescript-fundamentals-main (2)\typescript-fundamentals-main\node_modules\webpack-dev-server\lib\Server.js:3367:23)
    at new Promise (<anonymous>)
    at Server.start (C:\Chung\typescript-fundamentals-main (2)\typescript-fundamentals-main\node_modules\webpack-dev-server\lib\Server.js:3365:7)
    at async Command.<anonymous> (C:\Chung\typescript-fundamentals-main ***@***.***\serve\lib\index.js:158:21)
    at async Command.parseAsync (C:\Chung\typescript-fundamentals-main (2)\typescript-fundamentals-main\node_modules\webpack-cli\node_modules\commander\lib\command.js:935:5)
    at async Command.<anonymous> (C:\Chung\typescript-fundamentals-main (2)\typescript-fundamentals-main\node_modules\webpack-cli\lib\webpack-cli.js:1356:13)
    at async Command.parseAsync (C:\Chung\typescript-fundamentals-main (2)\typescript-fundamentals-main\node_modules\webpack-cli\node_modules\commander\lib\command.js:935:5) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 9000
}

Node.js v20.11.1

Thanks

Chung Lee
Software Engineer III
Reliance Technology Solution

Mobile:  (949) 285-3503
Email:   ***@***.******@***.***>

From: Dan Wahlin ***@***.***>
Sent: Friday, May 3, 2024 3:53 PM
To: DanWahlin/typescript-fundamentals ***@***.***>
Cc: Chung Lee ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [DanWahlin/typescript-fundamentals] Errors after running npm install (Issue #30)


CAUTION: This email originated from outside of the organization. Do not click links, open attachments or forward unless you recognize the sender and know the content is safe.





I'm not able to duplicate that on my Windows machine so I'd check the following:

  *   Make sure you have the latest Node LTS version as mentioned in the readme
  *   Ensure your npm is up to date (it should be fine if you have the latest Node LTS version): npm i -g npm
  *   Delete the node_modules folder and package-lock.json file from the project root and try running npm install again

If you're still having issues then I'd need more information about your Windows setup to try to help.

**Comment by DanWahlin** [comment]
The error shows that port 9000 is already in use on that machine. 

EADDRINUSE: address already in use :::9000 at Server.setupListenHandle

So, you'd either need to kill the process using that port on the machine or change the code to use a different port (the port is defined in webpack.config.js at the root of the project).

**Comment by rsaclee** [comment]
I am not an admin of the machine, so cannot open or kill any port.
It seems like your module is not suitable to run in a corporate environment with firewall protection and security enforced.

Thanks

Chung Lee
Software Engineer III
Reliance Technology Solution

Mobile:  (949) 285-3503
Email:   ***@***.******@***.***>

From: Dan Wahlin ***@***.***>
Sent: Monday, May 6, 2024 12:17 PM
To: DanWahlin/typescript-fundamentals ***@***.***>
Cc: Chung Lee ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [DanWahlin/typescript-fundamentals] Errors after running npm install (Issue #30)


CAUTION: This email originated from outside of the organization. Do not click links, open attachments or forward unless you recognize the sender and know the content is safe.





The error shows that port 9000 is already in use in that machine. So, good either need to kill that port or change the code to use a different port.

**Comment by DanWahlin** [comment]
I'm on a corporate machine right now. That's not the problem - we've literally had 1000s of people go through this, many on corporate devices. 

If you can't use port 9000 then find an open port (you might try 8080 for example) and modify the webpack file as mentioned. That's very normal with web development and not specific to this repo or code.

**Comment by rsaclee** [comment]
May I ask you to point out specifically which file to change the port number?

Thanks

Chung Lee
Software Engineer III
Reliance Technology Solution

Mobile:  (949) 285-3503
Email:   ***@***.******@***.***>

From: Dan Wahlin ***@***.***>
Sent: Tuesday, May 7, 2024 2:33 PM
To: DanWahlin/typescript-fundamentals ***@***.***>
Cc: Chung Lee ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [DanWahlin/typescript-fundamentals] Errors after running npm install (Issue #30)


CAUTION: This email originated from outside of the organization. Do not click links, open attachments or forward unless you recognize the sender and know the content is safe.





I'm on a corporate machine right now. That's not the problem - we've literally had 1000s of people go through this, many on corporate devices.

If you can't use port 9000 then find an open port (you might try 8080 for example) and modify the webpack file as mentioned. That's very normal with web development and not specific to this repo or code.

**Comment by DanWahlin** [comment]
It's the file that's mentioned in my earlier comment. Webpack.config.JS. Locate 9000 in the file and replace it with another port that is open on your machine. 8080 is normally an option on most machines, but it's something you'll have to try since it'll depend on your particular set up. Hope that helps.

**Comment by rsaclee** [comment]
It’s working!

Thanks

Chung Lee
Software Engineer III
Reliance Technology Solution

Mobile:  (949) 285-3503
Email:   ***@***.******@***.***>

From: Dan Wahlin ***@***.***>
Sent: Tuesday, May 7, 2024 2:42 PM
To: DanWahlin/typescript-fundamentals ***@***.***>
Cc: Chung Lee ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [DanWahlin/typescript-fundamentals] Errors after running npm install (Issue #30)


CAUTION: This email originated from outside of the organization. Do not click links, open attachments or forward unless you recognize the sender and know the content is safe.





It's the file that's mentioned in my earlier comment. Webpack.config.JS. Locate 9000 in the file and replace it with another port that is open on your machine. 8080 is normally an option on most machines, but it's something you'll have to try since it'll depend on your particular set up. Hope that helps.

**Comment by DanWahlin** [comment]
Awesome! Glad you were able to get it going.
